name: fibernet-cpu
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.9
- pytorch::pytorch
- jupyter
- scikit-learn
- scipy
- seaborn
- matplotlib
- tqdm
- umap-learn
- dipy
- fury
- tensorboard
- torchvision
- openpyxl